### ISSUE TITLE
Testing R with GitHub

### ISSUE THREAD

**Issue by Arjannikov** [mnesca/corgi_cubicle#1]
Currently, there is no code in your repository. You could create some R code (on your local machine) and _add_ the code file to the repository, then _commit_ and then _push_ the changes. If there were no errors, you should see the file appear on the GitHub website :)

On another note, you might find it useful to create a project in this repository. You can do it using the GitHub website, it is one of the tabs next to "Code", "Issues", "Pull requests"). Then you can manage your project Trello-style.

**Comment by mnesca** [comment]
thank you! for some reason my commit and push changes on R didnt update the github website yet.

**Comment by mnesca** [comment]
IT WORKS! Thanks Tom :)
