### ISSUE TITLE
How to save R markdown files on Github??

### ISSUE THREAD

**Issue by mnesca** [mnesca/corgi_cubicle#3]
Please let me know.

**Comment by mnesca** [comment]
![image](https://user-images.githubusercontent.com/51373047/60557479-52270200-9d0b-11e9-99ec-110115bd8bdc.png)

**Comment by mnesca** [comment]
I thought i solved the problem in the YAML but it didnt work. I knitted but i still have an error.

**Comment by mnesca** [comment]
Okay well i solved the issue of saving it to github but now i have a knitting issue.

**Comment by XuejingJiang** [comment]
Yaayy, Marcello! Good to know you solved the saving issue. If you are still struggling the knitting issue, we can discuss that ^_^
